pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: git
            image: alpine/git:latest
            command:
            - cat
            tty: true
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          - name: mariadb
            image: mariadb:latest
            env:
            - name: MYSQL_ROOT_PASSWORD
            value: "12345"
            ports:
            - containerPort: 3306
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
  stages {
    stage('Checkout') {
      steps {
        // Checkout your source code
        checkout scm
     }
  }
  stage('Build Docker Image') {
      steps {
        container('docker') {
          script {
            // Build the Docker image
            def appImage = docker.build("bahaben/dolibarr_repository:${env.BUILD_NUMBER}", "-f images/19.0.0-php8.2/Dockerfile .")
           echo 'duild success'
            // Push the Docker image to your Docker registry
                docker.withRegistry('', '10') {
                appImage.push()
                }
          }
        }
      }
    }
    }
  }
